### ISSUE TITLE
Installed 0.2.0 from Nuget for Droid project but assembly does not match code?

### ISSUE THREAD

**Issue by msivers** [halkar/xamarin-range-slider#1]
Having installed Xamarin.RangeSlider 0.2.0 into my Xamarin Droid project (Xamarin.RangeSlider.Droid) I can't see properties such as 'DefaultColor', 'ShowLabels', 'ThumbImage' etc. in intellisense. Looking at Xamarin.RangeSlider.Droid in the Assembly Browser and the RangeSliderControl class doesn't seem to match the latest code here on GitHub. The only public property seems to be 'NotifyWhileDragging'.

I have also tried version 0.1.6 and this too seems to be the same older version? 

I have downloaded and built latest and all works fine so it does seem as the Nuget packages are using older versions of code/assemblies.

**Comment by halkar** [comment]
Thanks a lot @msivers 

Looks like I packaged wrong version last time. Check out version 0.2.1.
