### ISSUE TITLE
Can't use in PCL project

### ISSUE THREAD

**Issue by rudyryk** [halkar/xamarin-range-slider#10]
```
Could not install package 'Xamarin.RangeSlider 0.5.7'.
You are trying to install this package into a project that targets
'.NETPortable,Version=v4.5,Profile=Profile78', but the package
does not contain any assembly references or content files that
are compatible with that framework. For more information,
contact the package author.
```

I believe that should not be a problem to provide PCL assembly for [`Xamarin.RangeSlider.Forms`](https://github.com/halkar/xamarin-range-slider/blob/master/Xamarin.RangeSlider.Forms/)

**Comment by rudyryk** [comment]
I see that issue #8 is the same case. Hmm... I think I'll try to build PCL assembly and make a PR.

**Comment by rudyryk** [comment]
I'm sorry, seems like I missed the fact there are actually 2 packages - one for Forms and one for "plain" Xamarin. Package for Forms is working with PCL - at least installing and compiling.

Probably this should be somehow highlighted in README.

**Comment by halkar** [comment]
@rudyryk thank! I'll update Readme to make it more clear.
