### ISSUE TITLE
1: error: No resource identifier found for attribute 'thumbShadowColor' in package 	

### ISSUE THREAD

**Issue by magtimmermans** [halkar/xamarin-range-slider#103]
Hi,

Since the latest release of Xamarin (Xamarin.Android 8.0.0.33) I have lots of errors with the slider on all attributes.

Like: 1: error: No resource identifier found for attribute 'thumbShadowColor' in package

the xaml version has reference to my package "com.yazula.android" like below:

        <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
            xmlns:local="http://schemas.android.com/apk/res/com.yazula.android"

this was working always but not anymore.

I have updated the range slider to the latest version but that did not help as well.

**Comment by halkar** [comment]
@magtimmermans I need sample project as I can't reproduce the issue.

**Comment by magtimmermans** [comment]
Ok, i will try to make this in the weekend. It is only with the latest xamarin release.

**Comment by magtimmermans** [comment]
Hi, I have e-mailed you the zip file to your google e-mail address. With the AppCompat the error appears. This gives only a problem in the latest VS 2017. VS2015 seems to work oke.

**Comment by magtimmermans** [comment]
Please open de file I send to your email address before November 11th. Otherwise it is expired. (Send by we transfer)

**Comment by magtimmermans** [comment]
Also possible to download here https://we.tl/JFmpFMQLYb

**Comment by halkar** [comment]
@magtimmermans please try updating your view axml to
```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <Xamarin.RangeSlider.RangeSliderControl
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/rangeSliderControl"
        app:absoluteMinValue="0"
        app:absoluteMaxValue="100"
        app:minThumbHidden="false"
        app:maxThumbHidden="false"
        app:showRangeLabels="true"
        app:alwaysActive="false"
        app:valuesAboveThumbs="true"
        app:barHeight="3dp" />
</LinearLayout>
```

**Comment by magtimmermans** [comment]
Perfect , works!
