### ISSUE TITLE
SetSelectedMinValue() and SetSelectedMaxValue() not working when called by RangeSlider events

### ISSUE THREAD

**Issue by AaronPerk** [halkar/xamarin-range-slider#105]
I'm trying to check to see that the user has at least 3 points selected in the range after the drag is completed, and to prohibit the min/max values from being set to break that rule. I'm hitting the lines where I call the methods to set the value, but when they fire it just doesn't do anything. Here's my code:

        private void RangeSlider_DragStarted(object sender, EventArgs e)
        {
            dragStartMinValue = rangeSlider.GetSelectedMinValue();
            dragStartMaxValue = rangeSlider.GetSelectedMaxValue();
        }

        private void RangeSlider_DragCompleted(object sender, EventArgs e)
        {
            float maxVal = rangeSlider.GetSelectedMaxValue();
            float minVal = rangeSlider.GetSelectedMinValue();

            if (dragStartMaxValue != maxVal)
            {
                if (!(maxVal - minVal > 1))
                {
                    RunOnUiThread(() => rangeSlider.SetSelectedMaxValue(dragStartMaxValue));
                }
            }
            else
            {
                if (!(maxVal - minVal > 1))
                {
                    RunOnUiThread(() => rangeSlider.SetSelectedMinValue(dragStartMinValue));
                }
            }
        }

**Comment by halkar** [comment]
@AaronPerk I've added `force` flag to `SetSelectedMaxValue` and `SetSelectedMinValue` methods. You can use it to update values while dragging.
