### ISSUE TITLE
Exception OnRestoreInstanceState (sometimes)

### ISSUE THREAD

**Issue by magtimmermans** [halkar/xamarin-range-slider#110]
Hi,

From some users I get the attached error message.

![error_range](https://user-images.githubusercontent.com/17949840/32701986-c7387626-c7df-11e7-9eac-9c8a30754774.png)

It seems as a problem in the control?

(Android).

**Comment by halkar** [comment]
@magtimmermans where is sample project and steps to reproduce the issue?

**Comment by magtimmermans** [comment]
Hi,

Well that's the problem, I cannot reproduce it but it happens to a number of users. I have talked with a few the users and it seems not consistent. It happens when entering the activity with the slider control on it. But not always. I have tested for memory issues, different os versions, rotation of the device. I had only one time this exception. It is only on Android.

**Comment by halkar** [comment]
@magtimmermans are you sure you pass correct `IParcellable` into the method? You should only use value received from the control's `OnSaveInstanceState` method.

**Comment by halkar** [comment]
Should be fixed in 0.8.1
