### ISSUE TITLE
RangeSlider binding to model

### ISSUE THREAD

**Issue by DusanSenior** [halkar/xamarin-range-slider#116]
Initial values are binded to activity correctly, but when it returns from page, the model is not changed by values entered by user (on the other hand f.e. Entry x:Name="Title" Text="{Binding Title }" is binded correctly). 
Code snippet is attached (xaml and cs in one file).
[_source.txt](https://github.com/halkar/xamarin-range-slider/files/1651589/_source.txt)

**Comment by esolzDotnet** [comment]
yes i am facing the same issue..
Any solution ?

**Comment by Viridovics** [comment]
@DusanSenior @esolzDotnet 
You can try this:
LowerValue="{Binding AmountMin, Mode=TwoWay}" 
UpperValue="{Binding AmountMax, Mode=TwoWay}"

**Comment by halkar** [comment]
Implemented in version 0.8.0.
