### ISSUE TITLE
[Android] Add material styling

### ISSUE THREAD

**Issue by kyle-john** [halkar/xamarin-range-slider#119]
[This project](https://github.com/oli107/material-range-bar) will help you.

**Comment by charlesroddie** [comment]
Suggest you do a fork to try this out.

**Comment by halkar** [comment]
Now, when we are using primitives instead of images it should be relatively easy. I'll try to implement material design later this week alongside with some other improvements.

**Comment by halkar** [comment]
Implemented in 0.7.31

**Comment by kyle-john** [comment]
@halkar I love it!
