### ISSUE TITLE
[UWP] Inconsistent crashes when slider min is dragged to max

### ISSUE THREAD

**Issue by charlesroddie** [halkar/xamarin-range-slider#121]
I have had this issue in my own project, and it occurs sometimes in the sample UWP project.
Sometimes it happens, sometimes it doesn't. On some systems, not on others.
I am working on this.
@halkar Currently the rangeslider is not in a good state with a few major bugs. I am intending to help. Are you still able to work at all on it yourself?

**Comment by charlesroddie** [comment]
On line 255 of RangeSliderControl.Xaml.cs of Xamarin.RangeSlider.UWP, min can take a value greater than RangeMax.

**Comment by halkar** [comment]
Fixed in 0.7.26.

@charlesroddie thanks a lot for your help. I really appreciate it.
