### ISSUE TITLE
Change Thumb size or Thumb image?

### ISSUE THREAD

**Issue by MikeW1986** [halkar/xamarin-range-slider#128]
in the readme is an example to change the Thumb color with a PlatformEffect, 
can you please provide also an example to change the Thumb size or Thumb image?

or is it possible to set an offset, because in my try the new thumb images are always displayed shifted.

Example in my PlatformEffect

      var ctrl = (Xamarin.RangeSlider.RangeSliderControl)Control;
      Context context = Android.App.Application.Context;
      Bitmap icon = BitmapFactory.DecodeResource(context.Resources, Resource.Drawable.thumbImage);
      ctrl.ThumbImage = icon;

**Comment by halkar** [comment]
The sample is here https://github.com/halkar/xamarin-range-slider#change-thumb-image Offset is 4,4,4,4

**Comment by halkar** [comment]
Fixed in 0.7.36
