### ISSUE TITLE
[Bug] Step value set, and thumb label

### ISSUE THREAD

**Issue by Magic73** [halkar/xamarin-range-slider#132]
Enabling thumb label, and using a step value will produce a label update even with the intermediate values while dragging.

I tried StepValueContinuously = false, but it doesn't works.

Example:
StepValueContinuously = false
ShowTextAboveThumbs = true          
LowerValue = 0
UpperValue = 5
MaximumValue = 0
MinimumValue = 100
StepValue = 1

now, drag the Max thumb.. and the user see the label updated with the intermediate values (5.1, 5.2, 5.3 ....) until you stop dragging, and the label is update with the right clamped value.

**Comment by Magic73** [comment]
My fault. 

Once set StepValueContinuously = true, it works as expected :)

Sorry :P

**Comment by halkar** [comment]
@Magic73 yes, you are right. The property name is misleading. The only reason why I'm not renaming it is that it is already used by a number of developers.
