### ISSUE TITLE
iOS build error

### ISSUE THREAD

**Issue by charlesroddie** [halkar/xamarin-range-slider#156]
```
MTOUCH : error MT2101: Can't resolve the reference 'System.String[] System.String::Split(System.Char,System.StringSplitOptions)', referenced from the method 'System.Boolean Xamarin.RangeSlider.RangeSliderControl::IS_PRE_IOS7()' in 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. [/Users/vsts/agent/2.146.0/work/1/s/Platforms/iOS/50iOS.csproj]
```
I can indeed see ios7 referred to in this repo:
https://github.com/halkar/xamarin-range-slider/search?q=IS_PRE_IOS7&unscoped_q=IS_PRE_IOS7

ios7 appears to be a very obsolete operating system http://gs.statcounter.com/ios-version-market-share/mobile-tablet/worldwide ; the minimum version with significant share is ios11.

@monkieboy @angelklim

**Comment by halkar** [comment]
Should be resolved now.
