### ISSUE TITLE
NullReferenceException:in Xamarin forms (iOS)

### ISSUE THREAD

**Issue by hirenvyas** [halkar/xamarin-range-slider#159]
Error Log: 
{System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.RangeSlider.Forms.RangeSliderRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x0031a] in <69b22edaf90846f898d4e87ca8cc9844>:0 

- when to come back from that slider page this error will be arise.
I am using Xamarin Forms (V 4.0) , Package (v 1.0.1) test in Iphone Xr iOS 12.2)

**Comment by halkar** [comment]
Do you have a sample app which reproduces the problem?

**Comment by alxlnk** [comment]
@hirenvyas I had same issue in Xamarin.Forms 4, because Control can be null.

I solved it by ovverriding RangeSliderRenderer.OnElementPropertyChanged method.

```
protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
{
	if (Control == null)
	{
		return;
	}

	base.OnElementPropertyChanged(sender, e);
}
```

I have also created pull request #160 for this issue.

**Comment by halkar** [comment]
Deployed in v1.0.2
Thanks @alxlnk
