### ISSUE TITLE
Thumb vector drawable crashed app.

### ISSUE THREAD

**Issue by roninua** [halkar/xamarin-range-slider#16]
I set vector drawable for thumb, normal, pressed, disabled a XML drawable.
I want to use my shapes, maybe vectorDrawable.

`var thumbNormal = Resource.Drawable.thumb_normal;`

_drawable/thumb_normal.xml :_

`<?xml version="1.0" encoding="UTF-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
  <solid android:color="#bada55"/>
  <stroke android:width="10dp" android:color="#fff" />
  <corners android:radius="10dp"/>
  <padding android:left="0dp" android:top="0dp" android:right="0dp" android:bottom="0dp" />
</shape>`

Error when i open activity widh slider:
`System.NullReferenceException: Object reference not set to an instance of an object.`

**Comment by halkar** [comment]
Thanks @roninua, I'll check it today.

**Comment by halkar** [comment]
@roninua I can't reproduce your issue

Activity layout
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <Xamarin.RangeSlider.RangeSliderControl
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:absoluteMinValue="10"
        app:absoluteMaxValue="50"
        app:valuesAboveThumbs="true"
        app:thumbNormal="@drawable/thumb_normal"
        app:thumbDisabled="@drawable/thumb_normal"
        app:thumbPressed="@drawable/thumb_normal" />
</LinearLayout>
```

thumb_normal
```
<?xml version="1.0" encoding="UTF-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
	<size android:width="40dp" android:height="40dp" />
	<solid android:color="#bada55" />
	<stroke android:width="10dp" android:color="#fff" />
	<corners android:radius="10dp" />
	<padding android:left="0dp" android:top="0dp" android:right="0dp" android:bottom="0dp" />
</shape>
```

**Comment by halkar** [comment]
@roninua can you share small project reproducing issue?

**Comment by halkar** [comment]
Or if you can provide me with full stack trace.

**Comment by halkar** [comment]
@roninua ping!

**Comment by halkar** [comment]
@roninua if you are still experiencing this issue please comment and reopen.
