### ISSUE TITLE
Feature request: allow separate text formatting for lower and upper values

### ISSUE THREAD

**Issue by rudyryk** [halkar/xamarin-range-slider#17]
Currently we have a `TextFormat ` property, it would be great to have extra optional `LowerTextFormat ` and `UpperTextFormat` ones.

For example, I'd want to treat maximum upper value as unlimited and display "Unlimited" label when upper handler is at right most position.

**Comment by halkar** [comment]
@rudyryk hm... interesting, will add this to the backlog.

**Comment by halkar** [comment]
@rudyryk  I've added `FormatLabel` method which you can use to format label as you like. Please check out v0.6.5.

**Comment by halkar** [comment]
@rudyryk  sorry, v0.6.5 is broken, please check out v0.6.6.
