### ISSUE TITLE
Great control but could do with some more customisation options.

### ISSUE THREAD

**Issue by msivers** [halkar/xamarin-range-slider#2]
A couple of things that would be really useful (commonly so).

1. Typically sliders would have an increment setting so that you can force increments of a defined amount. I.e. the selection would jump by a step value e.g. value of 25. Therefore a min value of 100 and max value of 200 would have 5 steps in total... 100, 125, 150, 175, 200. This is very much required for me. 

2. I really need to be able to define text formatting for the text above the slider handles... for example, I would like to have the selected value be represented as a currency. I.e. £75

3. Thickness of slider's line (and/or make a drawable). I would like to be able to have the line be thicker i.e. 6dp in height.

Anything you could do to implement the above would be massively appreciated?!... I await you feedback.  👍🏼

**Comment by halkar** [comment]
Sorry for the delay.

1. This will be next feature to implement.
2. Text above handles at the moment is implemented only on Android (valuesAboveThumbs in axml or ShowTextAboveThumbs in code). But I will think of implementing this feature.
3. On Android it is only available in axml as barHeight.

I will close this one as I created separate tasks.

**Comment by halkar** [comment]
@msivers I've updated nuget packages. You can give them a try.
