### ISSUE TITLE
NullReferenceException in UWP when unloading the control

### ISSUE THREAD

**Issue by CodePhobie** [halkar/xamarin-range-slider#23]
In the file _Xamarin.RangeSlider.Forms.WinRT.Shared\RangeSeekBarRenderer.cs_ Line: 25 in method _OnElementChanged_ causes an exception when the RangeSlider gets unloaded. The property _Element_ is NULL.

**Comment by halkar** [comment]
Thanks @CodePhobie, will investigate.

**Comment by halkar** [comment]
@CodePhobie I've updated the nuget packages. Could you please check if exception persists in version 0.6.3?

**Comment by CodePhobie** [comment]
Perfect, problem fixed, it works like a charm 👍 
Thank you
