### ISSUE TITLE
Error with Nuget Package on Xamarin iOS

### ISSUE THREAD

**Issue by CatherineSD** [halkar/xamarin-range-slider#25]
I'm using the nuget package on Xamarin iOS and I've added a Range Slider Control to one of my View Controller in the storyboard. Each time I have to change the view controller containing the slider, the designer file of my view is changed and write:
`[GeneratedCode ("iOS Designer", "1.0")]
Xamarin.RangeSlider.RangeSeekBar MyRange { get; set; }`

This cause the error "Xamarin.RangeSlider.RangeSeekBar is inaccessible due to its protection level". To fix the problem, I have to change the "RangeSeekBar" to "RangeSliderControl" in the designer file, but I need to do this everything the designer is changed.

Is there any fix for this?
Thanks.

**Comment by halkar** [comment]
Thanks @CatherineSD 
I believe I know why it happens. Will try to fix this issue today.

**Comment by halkar** [comment]
@CatherineSD can you try adding `var type = typeof(RangeSliderControl);` somewhere in your `AppDelegate.FinishedLaunching`?

**Comment by CatherineSD** [comment]
@halkar  Thanks for your response. I tried what you said but I don't know how it could help, because the error "Xamarin.RangeSlider.RangeSeekBar is inaccessible due to its protection level" appears on compilation...

**Comment by halkar** [comment]
thanks @CatherineSD, that helps!

**Comment by halkar** [comment]
@CatherineSD try downloading new nuget packages v 0.6.4

**Comment by CatherineSD** [comment]
Thanks @halkar , I downloaded the new package and the problem seems to be fixed :) I will contact you if I encounter this bug again!

**Comment by halkar** [comment]
Thanks @CatherineSD
