### ISSUE TITLE
System.Reflection.TargetInvocationException on iPhone

### ISSUE THREAD

**Issue by CodePhobie** [halkar/xamarin-range-slider#27]
Hi,
tried to run an app using your Range-Slider on an iPhone today. Unfortunately caused the package an error at runtime:
_System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xamarin.Forms.Xaml.XamlParseException: Position 110:10. Type forms:RangeSlider not found in xmlns clr-namespace:Xamarin.RangeSlider.Forms;assembly=Xamarin.RangeSlider.Forms\n  at Xamarin.Forms.Xaml.CreateValuesVisitor.Visit (Xamarin.Forms.Xaml.ElementNode node, Xamarin.Forms.Xaml.INode parentNode) [0x00040]_
Namespace declaration:
 _xmlns:forms="clr-namespace:Xamarin.RangeSlider.Forms;assembly=Xamarin.RangeSlider.Forms"_
Used the latest version 0.6.4 of the Xamarin.Forms.RangeSlider and Xamarin.RangeSlider.
Can you use the RangeSlider on an iOS device? Do I need to add the ExportRendererAttribute to my iOS AppDelegate class, like in your example?
Thanks for your help

**Comment by halkar** [comment]
@CodePhobie yes, you need to add something like this in your `AppDelegate`
<img width="666" alt="screen shot 2016-11-25 at 06 05 55" src="https://cloud.githubusercontent.com/assets/1992396/20608357/5d6d8f58-b2d5-11e6-819e-a3241db92942.png">

**Comment by halkar** [comment]
@CodePhobie does it fix your issue?

**Comment by halkar** [comment]
Closing the issue.

**Comment by CodePhobie** [comment]
Yes, adding the attribute fixed the problem. 
Don't have an own iPhone, so I could test it just now.
Thx
