### ISSUE TITLE
Feature request: allow to add culture variant textformat

### ISSUE THREAD

**Issue by CatherineSD** [halkar/xamarin-range-slider#30]
Hi, this is an improvement request. For now, with the textFormat, it is possible the use "C" to specify currency, but we cannot specify which culture to use (e.g. american dollar, canadian dollar, etc.) It would be great to have a field to specify which culture to use in the format :)

Thanks!

**Comment by halkar** [comment]
@CatherineSD to make it clear. Do you want to use currency different to your current local settings?

**Comment by CatherineSD** [comment]
@halkar Yes, to be able to have something similar to String.Format(culture, format, value); where culture can be set like: culture = CultureInfo.CreateSpecificCulture("da-DK").

**Comment by halkar** [comment]
Hm.. ok, should be easy to implement.

**Comment by CatherineSD** [comment]
Thanks a lot for your help!

**Comment by halkar** [comment]
@CatherineSD no worries, just don't expect new version to be released before the end of this weekend.

**Comment by CatherineSD** [comment]
@halkar It's ok for me :)

**Comment by halkar** [comment]
@CatherineSD I've added `FormatLabel` method which you can use to format label as you like. Please check out v0.6.5.

**Comment by halkar** [comment]
@CatherineSD sorry, v0.6.5 is broken, please check out v0.6.6.

**Comment by CatherineSD** [comment]
@halkar Thanks, I will try it today.

**Comment by CatherineSD** [comment]
@halkar I updated to the last package in my project. When trying to set the FormatLabel, I get the error "The type Xamarin.RangeSlider.Common.Thumb is defined in an assembly that is not referenced. Consider adding a reference to assembly 'Xamarin.RangeSlider.Common'...". I tried to remove and readd the package, closing Xamarin Studio and reopening it, but it does not seems to update the references. Do you have a idea to fix this?

**Comment by halkar** [comment]
@CatherineSD please check that you are working with v0.6.6 and not v0.6.5.

**Comment by CatherineSD** [comment]
@halkar I check on both Android and iOS that the package is v0.6.6, but the problem remains. I even tried to create a new project and add the v0.6.6 package, but with that version, I can't even add a RangeSlider control in the storyboard. I have to backtrack to v0.6.4 to add the control.

**Comment by halkar** [comment]
@CatherineSD thanks!

**Comment by halkar** [comment]
Sorry @CatherineSD, please check out v0.6.7.

**Comment by CatherineSD** [comment]
@halkar Everything works perfectly now! Thanks for your time :)
