### ISSUE TITLE
[Android] [iOS] [UWP] Thumb labels overlap

### ISSUE THREAD

**Issue by halkar** [halkar/xamarin-range-slider#34]
![simulator screen shot 9 dec 2016 21 09 51](https://cloud.githubusercontent.com/assets/1992396/21045292/e5d0d42a-be53-11e6-862a-5835737f519b.png)

**Comment by rvlira** [comment]
Hi! I just got this issue on iOS and what's messing with my head is that I implemented that on Android and it works.

I had a look on iOS version code (trying to come up at least with a workaround) but I'm new enough on iOS that I only know positioning through constraints (autolayout). This component seems to use a different method.

**Comment by halkar** [comment]
fixed in 0.7.8
