### ISSUE TITLE
UWP Compiler Warning 'Detected package downgrade'

### ISSUE THREAD

**Issue by CodePhobie** [halkar/xamarin-range-slider#40]
The _Xamarin.Forms.RangeSlider_ package causes compiler warnings in VisualStudio 2015 when using it in an UWP-App:
_Warning: Detected package downgrade: Xamarin.Forms from 0.0.0 to 2.3.3.175 
 App.UWP (>= 1.0.0) -> Xamarin.Forms.RangeSlider (>= 0.6.8) -> Xamarin.Forms  
 App.UWP (>= 1.0.0) -> Xamarin.Forms (>= 2.3.3.175)_

**Comment by halkar** [comment]
`Xamarin.Forms.RangeSlider` doesn't have any version requirements for `Xamarin.Forms`.

**Comment by halkar** [comment]
Fixed in https://github.com/halkar/xamarin-range-slider/pull/52
