### ISSUE TITLE
Lower value is incorrect when MinimumValue is not 0

### ISSUE THREAD

**Issue by pvillads** [halkar/xamarin-range-slider#41]
The control is currently useless, since the system will not work with Minimum values greater than 0. Say the minimum value property is 40 and you set the Lower value to 50, the reading is set to 90, not 50, since 90 = 40 + 50.

This is not true for the UpperValue, in which case it would be consistent, at least. You can see this behavior in the attached project. It simply defines a page with a slider on it, and sets up a trivial Viewmodel, does two way binding to it.

I hope this is enough to fix the problem.

[XlabRangeSlidertTest.zip](https://github.com/halkar/xamarin-range-slider/files/664946/XlabRangeSlidertTest.zip)

**Comment by halkar** [comment]
@pvillads is it on Android/iOS/UWP?

**Comment by halkar** [comment]
@pvillads I've tested on Android and iOS.
At the moment in your sample I see both Lower and Upper values changing from 40 to 200. Same changes are reflected in the view-model.
<img width="112" alt="screen shot 2016-12-21 at 10 09 15" src="https://cloud.githubusercontent.com/assets/1992396/21371449/902d280a-c765-11e6-9095-b6c33e4c2062.png">
<img width="399" alt="screen shot 2016-12-21 at 10 09 07" src="https://cloud.githubusercontent.com/assets/1992396/21371450/902ddbe2-c765-11e6-9171-588a22785ea0.png">

**Comment by pvillads** [comment]
Artur,

Thank you for devoting some attention to this issue.

I can repro the problem at will on 0.6.9. The way to do it is simply to open the project and run on android. When you do, you will see that the low value is set to 90, not 50, as it should be. It is perfectly possible to drag the slider at will; the problem is that it starts with the wrong value

I am running on the newest version of everything.

[cid:image001.png@01D25BA0.F82B54D0]

**Comment by halkar** [comment]
Thanks @pvillads. I managed to reproduce the issue. Working on it.

**Comment by halkar** [comment]
Thanks @pvillads. Should be fixed in v0.6.10.

**Comment by pvillads** [comment]
Confirming that 0.6.10 solves the problem

**Comment by halkar** [comment]
Thanks for your help @pvillads!
