### ISSUE TITLE
The rangeslider does not render on windows phone

### ISSUE THREAD

**Issue by pvillads** [halkar/xamarin-range-slider#43]
The windows phone version of the rangeslider does not render. Repro: Build a simple page with a range slider (you may repro with the sample I already provided for another problem). The WP screen will be blank, and not show a range slider.

I suspect the problem is that the correct assemblies are not installed as part of the nuget install. I only see references to:

xamarin.rangeslider.common
xamarin.rangeslider..Forms

in the windows phone project, whereas the Droid version in addition references

xamarin.rangeslider.Droid
xamarin.rangeslider.Forms.Droid

in which the renderer is contained.

**Comment by halkar** [comment]
@pvillads just to make thing clear Windows Phone is Windows Phone or UWP. Windows Phone is not supported.
