### ISSUE TITLE
Rendering rangeslider on UWP results in an exception

### ISSUE THREAD

**Issue by pvillads** [halkar/xamarin-range-slider#44]
Please reuse the repro project I submitted for a previous problem.

When running the form with UWP an exception is thrown:

Could not load file or assembly 'System.Runtime.WindowsRuntime.UI.Xaml, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

rendering the control unfunctional.

**Comment by halkar** [comment]
Fixed in https://github.com/halkar/xamarin-range-slider/pull/53
Will be available in next release.
