### ISSUE TITLE
Windows 8.1 projects with rangeslider do not compile

### ISSUE THREAD

**Issue by pvillads** [halkar/xamarin-range-slider#45]
Please repro with the previously submitted project

Make the Windows 8.1. project the current project and build. You will get these build errors:

The type or namespace name 'ExportRendererAttribute' does not exist in the namespace 'Xamarin.Forms' (are you missing an assembly reference?)
The type or namespace name 'ExportRenderer' does not exist in the namespace 'Xamarin.Forms' (are you missing an assembly reference?)

BR PV

**Comment by halkar** [comment]
Fixed in https://github.com/halkar/xamarin-range-slider/pull/54
