### ISSUE TITLE
Attribute already defined issue.

### ISSUE THREAD

**Issue by NishaSlb** [halkar/xamarin-range-slider#49]
Hi, 

I am getting following error:

"Attribute Showlabel" is already been defined.

 I am using telerik in my project and whenever I add Range slider in my package and compile the project I get the above mentioned error for android.

Can you please help me in resolving the issue.

Regards,
Nisha

**Comment by halkar** [comment]
Thanks @NishaSlb 

Can you provide some small test project reproducing the issue?

**Comment by NishaSlb** [comment]
Following is the link from where you can download the sample project.

https://github.com/Akshay1988/Range-Slider-CompilationIssue.git

When I compile the above project I get following error.

Error APT0000: Attribute "showLabels" has already been defined (APT0000) 

Appreciate your help :)

**Comment by NishaSlb** [comment]
Have you find the solution to the above problem ?

**Comment by NishaSlb** [comment]
Artur,

Please let me know if you need any more information regarding the same.

Can you please look into this on priority.

Regards,
Nisha

**Comment by halkar** [comment]
@NishaSlb sorry, I'll check it out tomorrow.

**Comment by halkar** [comment]
@NishaSlb I can build your project without any issue. And `RangeSlider` is not used on the page. Is this how you wanted it to be?

**Comment by halkar** [comment]
Adding RangeSlider into the page doesn't break the project too.

**Comment by NishaSlb** [comment]
I have used Range slider in my project for both ios and android.
Its working fine on IOS but for android when I compile it gives me that error.
When I remove the range slider package from my Application, the app compiles fine.

**Comment by halkar** [comment]
Weird.

**Comment by NishaSlb** [comment]
Are you able to see charts ?

**Comment by NishaSlb** [comment]
Are you able to run the application on the phone(Android) and see the chart ?

**Comment by halkar** [comment]
@NishaSlb which Android version are you running?

**Comment by halkar** [comment]
I've tried Android 6.0.1 and 7.1.1 on real devices, and 5.0 on emulator.

**Comment by NishaSlb** [comment]
I tried on Android 6.0 (real device)[API 23]

Xamarin Studio (6.1.1)

Xamarin.Android
Version: 6.1.2.21 (Xamarin Enterprise)
Android SDK: 
	Supported Android versions:
		6.0 (API level 23)

SDK Tools Version: 25.2.3
SDK Platform Tools Version: 25.0.1
SDK Build Tools Version: 23.0.2

**Comment by NishaSlb** [comment]
I updated my Xamarin studio and Xamarin Android to the latest version, but still it is not working.

I think Showlabel attribute is only used once in attr file in RangeSlider, Is it possible for you to rename it ?

**Comment by halkar** [comment]
Thanks! I'll try to work on this today.

**Comment by halkar** [comment]
Fixed in https://github.com/halkar/xamarin-range-slider/pull/56

**Comment by NishaSlb** [comment]
Thanks Artur :)
