### ISSUE TITLE
Range Slider in UWP

### ISSUE THREAD

**Issue by hsl2017** [halkar/xamarin-range-slider#50]
Hi,

I meet a problem when using it.
In UWP, when the page appearing, if the lower value is not equal to the minvalue, the upper value is always equal to the lower value.

Firstly I thought there was something wrong when binding, but then I try this:

    
                                      <forms:RangeSlider Grid.Row="0" 
                                     ShowTextAboveThumbs="True"  MinimumValue="0" MaximumValue="100"
                                     LowerValue="50"
                                     UpperValue="75" >

Both LowerValue and UpperValue are set as 50 when the page is appearing.
Only in UWP.

Can you help me on this? 
Thank you.

**Comment by halkar** [comment]
I'll take a look on this one.

**Comment by hsl2017** [comment]
Hi, Halkar, is this problem still there?

**Comment by halkar** [comment]
Yes, haven't had a chance to fix. Will try to work on this one today/tomorrow.

**Comment by hsl2017** [comment]
Thank you!

**Comment by halkar** [comment]
Fixed in https://github.com/halkar/xamarin-range-slider/pull/55
