### ISSUE TITLE
Android: Not able build the application.

### ISSUE THREAD

**Issue by blahiry** [halkar/xamarin-range-slider#51]
Hi Artur,
I am facing a issue like "showLabels" already defined when I am trying to build the application in android. I am using telerik dlls in my application to create some charts and your RangeSlider to select a time period. Now inside "attr.xaml" there is a attribute named "showLabels", which is making a issue for me. Need your help sir.

**Comment by halkar** [comment]
https://github.com/halkar/xamarin-range-slider/issues/49
