### ISSUE TITLE
How to change the Thumb color using a PlatformEffect?

### ISSUE THREAD

**Issue by CodePhobie** [halkar/xamarin-range-slider#59]
Hi, 
how is it possible to change the color of the thumb using a PlatformEffect on Android and iOS?
For the normal _Slider_ (Android _SeekBar_; iOS _UISlider_) it is very simple:
https://blog.xamarin.com/customizing-xamarin-forms-controls-with-effects/ 

Changing the _ActiveColor_ of the _RangeSlider_ is also easy but the thumb of the _RangeSlider_ is a _Bitmap_ and not a _Drawable_. Do you have a suggestion how the color of the Thumb can be easily changed?

Thank you

**Comment by halkar** [comment]
Ok, there is no "easy" way. But why not to create a drawable and use it?

**Comment by halkar** [comment]
Anyway, I'll try to work something out.

**Comment by CodePhobie** [comment]
Found an easy way to theme your RangeSlider.
**Here is the solution for Android:**
`using Android.Graphics;
using Android.Graphics.Drawables;
using Xamarin.Forms;
using Xamarin.Forms.Platform.Android;

[assembly: ExportEffect(typeof(Droid.Effects.RangeSliderEffect), nameof(Droid.Effects.RangeSliderEffect))]

namespace Droid.Effects
{
    public class RangeSliderEffect : PlatformEffect
    {

        protected override void OnAttached()
        {
            var themeColor  = Xamarin.Forms.Color.Orange.ToAndroid();
            var ctrl         = (Xamarin.RangeSlider.RangeSliderControl)Control;
            ctrl.ActiveColor = themeColor;

            var thumbImage = new BitmapDrawable(ctrl.ThumbImage);
            thumbImage.SetColorFilter(new PorterDuffColorFilter(themeColor, PorterDuff.Mode.SrcIn));
            ctrl.ThumbImage = ConvertToBitmap(thumbImage, ctrl.ThumbImage.Width, ctrl.ThumbImage.Height);

            var thumbPressedImage = new BitmapDrawable(ctrl.ThumbPressedImage);
            thumbPressedImage.SetColorFilter(new PorterDuffColorFilter(themeColor, PorterDuff.Mode.SrcIn));
            ctrl.ThumbPressedImage = ConvertToBitmap(thumbPressedImage, ctrl.ThumbPressedImage.Width, ctrl.ThumbPressedImage.Height);
        }

        protected override void OnDetached()
        {
        }

        private static Bitmap ConvertToBitmap(Drawable drawable, int widthPixels, int heightPixels)
        {
            var mutableBitmap = Bitmap.CreateBitmap(widthPixels, heightPixels, Bitmap.Config.Argb8888);
            var canvas        = new Canvas(mutableBitmap);
            drawable.SetBounds(0, 0, widthPixels, heightPixels);
            drawable.Draw(canvas);

            return mutableBitmap;
        }
    }
}`

**Comment by mariolobar** [comment]
Hi
How can apply the effect?
And have you got the same in iOS?
Thank you

**Comment by CodePhobie** [comment]
@mariolobar here is a good tutorial how to use effects:
https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/effects/creating/ 

On iOS I changed only the color of the selected range and not of the thumb:

`using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;

[assembly: ExportEffect(typeof(iOS.Effects.RangeSliderEffect), nameof(iOS.Effects.RangeSliderEffect))]

namespace Flatmatch.iOS.Effects
{
    public class RangeSliderEffect : PlatformEffect
    {
        protected override void OnAttached()
        {
			var themeColor  = Xamarin.Forms.Color.Orange.ToAndroid();
            var ctrl        = (Xamarin.RangeSlider.RangeSliderControl)Control;

            ctrl.TintColor = themeColor.ToUIColor();
        }

        protected override void OnDetached()
        {
        }
    }
}`

**Comment by halkar** [comment]
I will try to make thumbs editable but it requires some changes.

**Comment by halkar** [comment]
@mariolobar I've updated readme to make it more clear how to customize slider.
