### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by opcodewriter** [halkar/xamarin-range-slider#6]
I added the library by NuGet but I get compilation errors.

![snip_20160907091325](https://cloud.githubusercontent.com/assets/15019084/18301619/8cacd3e2-74db-11e6-8f2f-fa4dba109b0b.png)

**Comment by halkar** [comment]
@opcodewriter do you use it with Xamarin.Forms or with Xamarin.Droid?

**Comment by halkar** [comment]
@opcodewriter thanks!
Should be fixed in 0.5.4.
