### ISSUE TITLE
[iOS] Getting "Unknown class RangeSlider in Interface Builder file."

### ISSUE THREAD

**Issue by rvlira** [halkar/xamarin-range-slider#63]
After creating a new Universal Single View Xamarin.iOS  app project on Visual Studio 2015, I installed RangeSliderControl using the nuget package.

I was able to drag the control from the toolbox to the storyboard and configure all settings.

When I try to run the project, I get this message: "Unknown class RangeSlider in Interface Builder file". The component does not show on the emulator when running the app.

Is there any extra step to use it via interface builder?

Thanks.

**Comment by halkar** [comment]
@rvlira should work without any additional effort. I'll check.
Thank you!

**Comment by halkar** [comment]
@rvlira problem is in Xamarin iOS linker behavior.

Just add `var t = typeof(RangeSliderControl);` somewhere in your `AppDelegate.cs` to prevent `RangeSliderControl` from being excluded from the build.
