### ISSUE TITLE
[iOS] Problem with setting the UpperValue and LowerValue programmatically

### ISSUE THREAD

**Issue by xplatsolutions** [halkar/xamarin-range-slider#64]
Setting the UpperValue and LowerValue programmatically after the View is appeared does not update the control until it receives a touch event in the View area.

In my XIB I have a UIView where I set the class to `RangeSlider` and setting initial values, works great! Strange issue is after the View appears I set the LowerValue and UpperValue programmatically again but nothing happens until the RangeSlider receives a touch event, just by tap on the view it moves the slider knobs according to what I set it to.

Any idea?

**Comment by xplatsolutions** [comment]
Calling SetNeedsLayout in ViewWillLayoutSubviews did the job. I would recommend callign this method maybe when setting the UpperValue and LowerValue.

**Comment by halkar** [comment]
Thanks @xplatsolutions

**Comment by xplatsolutions** [comment]
No problem, thanks for the RangeSlider :-)

**Comment by halkar** [comment]
Fixed in 0.6.17.
