### ISSUE TITLE
Moving slider rapidly crashes the app

### ISSUE THREAD

**Issue by henrick-tissink** [halkar/xamarin-range-slider#66]
Hi, 

I'm currently using this slider in my app, and moving the slider rapidly seems to crash the iOS version of the app. The android version is fine.

The crash seems to occur when the values get set in the element,

        public void OnLowerValueChanged(float value)
        {
            LowerValue = value;
            LowerValueChanged?.Invoke(this, EventArgs.Empty);
        }

        public void OnUpperValueChanged(float value)
        {
            UpperValue = value;
            UpperValueChanged?.Invoke(this, EventArgs.Empty);
        }

If I comment out the assignment, 

        public void OnLowerValueChanged(float value)
        {
            //LowerValue = value;
            LowerValueChanged?.Invoke(this, EventArgs.Empty);
        }

        public void OnUpperValueChanged(float value)
        {
            //UpperValue = value;
            UpperValueChanged?.Invoke(this, EventArgs.Empty);
        }

it doesn't crash, but the labels don't get updated. 

Any help with this will be greatly appreciated.

**Comment by halkar** [comment]
Thanks @henrick-tissink 
I'll have a look as soon as I can.

**Comment by henrick-tissink** [comment]
Hi Halkar,

Seemed to be a problem in a currency converter in our app. 

Sincerest apologies, and thanks for the great slider!
