### ISSUE TITLE
Add support for .net standard

### ISSUE THREAD

**Issue by halkar** [halkar/xamarin-range-slider#71]

**Comment by charlesroddie** [comment]
Any progress on this @halkar . Is the rangeslider usable yet from .net standard Xamarin projects?

**Comment by charlesroddie** [comment]
We migrated to .Net Standard 2.0 and there were no new rangeslider problems. So I think it's compatible already.

**Comment by kyle-john** [comment]
Is it in progress?

**Comment by amoscatelli** [comment]
OH so there was an issue for this. Really good.
Yea I am really interested in ufficial support for .Net Standard 2.0

**Comment by halkar** [comment]
Implemented in 1.0.0
