### ISSUE TITLE
Label text color

### ISSUE THREAD

**Issue by bandito707** [halkar/xamarin-range-slider#73]
Is it possible to modify the text color above the thumbs?

**Comment by halkar** [comment]
@bandito707 at the moment you can change text color on Android but not on other platforms. See https://github.com/halkar/xamarin-range-slider#change-thumb-image to find how to access platform-specific properties.

**Comment by halkar** [comment]
Implemented in 0.7.0

**Comment by ankit0092** [comment]
Hey, I am not able to find v0.7.0 in nuget.

**Comment by halkar** [comment]
@ankit0092 it's hidden. You can install it by specifying nuget version `Install-Package Xamarin.RangeSlider -Version 0.7.2`
