### ISSUE TITLE
Is not visible in UWP

### ISSUE THREAD

**Issue by hejjahejja** [halkar/xamarin-range-slider#74]
The entire component is gone. Works in Android.
Running latest version of the slider.

**Comment by halkar** [comment]
@hejjahejja do you have a sample project to reproduce the issue?

**Comment by hejjahejja** [comment]
@halkar I'll get you one. By the way I'm debugging my UWP with 'Local machine', does it matter?

**Comment by halkar** [comment]
@hejjahejja thanks! No, the element should work in any environment.

**Comment by hejjahejja** [comment]
Weird, I created a new project. The slider was there, went back to the project where the problem were. But it worked. So perhaps this should be closed. 
Another thing that I notice, If it's only a tag like this '<forms:RangeSlider />, then there are nothing to drag. I needed to set lower and upper value.
