### ISSUE TITLE
Could not add Xamarin.RangeSlider 0.5.7

### ISSUE THREAD

**Issue by retepel** [halkar/xamarin-range-slider#8]
Could not install package 'Xamarin.RangeSlider 0.5.7'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by halkar** [comment]
If you are working with Xamarin.Forms just add Xamarin.Forms.RangeSlider package to all your projects. Xamarin.RangeSlider is only for platform-specific projects.
