### ISSUE TITLE
Android: can't build

### ISSUE THREAD

**Issue by Goldstrike** [halkar/xamarin-range-slider#80]
Hello,

I tried to build the Xamarin.Forms Droid sample but it didn't work.

I get some errors in the "values.xml" file, as we can see in this [screenshot](https://img4.hostingpics.net/pics/565039AndroidErrorsValuesXml.png).

Would you have any explanation? For iOS and UWP I get no problem...

**Comment by halkar** [comment]
@Goldstrike considering that all those errors are not related to my code you need to check if you have the correct version of Android SDK installed on your machine.

**Comment by Goldstrike** [comment]
Which version of Android are you using?
I've tried to migrate the Target Framework from Android 7.1 to Android 6.0, but this didn't change anything...
I have up to date the [Android SDK Manager](https://img4.hostingpics.net/pics/678185AndroidSdkManager.png), but I always have the same error.
Finally, I asked a colleague to test the sample on it's computer: he meets the same problem than me.

**Comment by halkar** [comment]
@Goldstrike just to make things clear, are you trying to build the library itself or your project uses library/nuget?

**Comment by Goldstrike** [comment]
I try to build the sample project (Xamarin.RangeSlider.Forms.Samples.Droid)

**Comment by halkar** [comment]
@Goldstrike check out latest master.

**Comment by Goldstrike** [comment]
Thank you it works fine now!
