### ISSUE TITLE
Win8.1: measurements wrong when setting BarHeight and MinThumbHidden

### ISSUE THREAD

**Issue by charlesroddie** [halkar/xamarin-range-slider#83]
Minor issue on Win8.1 (not relevant on iOS, untested on Android). When BarHeight is set to an int, and MinThumbHidden is true, the range color does not extend the right distance.

With MinThumbHidden=true

BarHeight not set :
![rangeslider2](https://user-images.githubusercontent.com/19760720/29715563-c05ee034-899f-11e7-8e26-61f44d45ed9a.PNG)

BarHeight = Nullable<int>(8) :
![rangeslider](https://user-images.githubusercontent.com/19760720/29715514-863d5dea-899f-11e7-9b0c-a4bdd4dbf032.PNG)

In these examples LowerValue = MinimumValue so the colored range should extend all the way to the left.

Thanks for this great component!

**Comment by halkar** [comment]
fixed in 0.7.5
