### ISSUE TITLE
How to enable click/tap on range slider?

### ISSUE THREAD

**Issue by jameswilliams00789** [halkar/xamarin-range-slider#84]
I just start using this plugin but when I try to tap/tap  (instead of dragging to update value), it doesn't work. how can I do it to act similar to normal slider?

**Comment by halkar** [comment]
@jameswilliams00789 what's your platform? second, device? third, do you have sample project reproducing the issue?

**Comment by halkar** [comment]
@jameswilliams00789 problem is that having two handles it is impossible to tell which value (lower or upper) should be changed so I don't understand how to implement this feature. If you have any ideas please share.
