### ISSUE TITLE
Effect on UWP

### ISSUE THREAD

**Issue by predalpha** [halkar/xamarin-range-slider#85]
Hello @halkar ,

refering to https://github.com/halkar/xamarin-range-slider/issues/59

I want to know if it is possible to theme / style RangeSlider for UWP projects.
Effects working fine on Android but on UWP there are no exposed color properties or maybe i havent found any solution to change bar / thumbs colors.

Is this possible ? If not will you implement those features ?

Regards

**Comment by halkar** [comment]
Made all element public in 0.7.6. You can access them and change their properties using effects.
