### ISSUE TITLE
Android: Cannot set LowerValue

### ISSUE THREAD

**Issue by thetrust3343** [halkar/xamarin-range-slider#86]
I currently try to give the rangeslider some standard values.
MinimumValue is 1 and Maximum is 5.
After that i set the LowerValue to 2 (With a variable) and the UpperValue to 5.
In iOS that works perfectly but in android its just a range from 1 to 5 instead of 2 to 5.

**Comment by halkar** [comment]
@thetrust3343 do you have a sample project reproducing the problem?

**Comment by thetrust3343** [comment]
@halkar here an pretty easy sample https://github.com/thetrust3343/RangeSlider_LowerValue_SampleApp

**Comment by halkar** [comment]
fixed in 0.7.4
