### ISSUE TITLE
[IOS] Throw Exception when MinimumValue and MaximumValue are equals

### ISSUE THREAD

**Issue by LuisM000** [halkar/xamarin-range-slider#87]
Hi. I have a problem in IOS (Xamarin forms) when I set the minimum and maximum values equal. For example:
`<forms: RangeSlider MinimumValue = "1" MaximumValue = "1" />`
Throws an exception.
Reviewing the code, the problem is in the Xamarin.RangeSlider.IOS project, in the TrackRect() function of the RangeSliderControl class (NaN values ..).
Any solution?

Thank you.
Greetings,

Luis

**Comment by halkar** [comment]
@LuisM000 unless you really need to don't set `MinimumValue` and `MaximumValue` to the same value. Bug is legit and I'll fix it but I see no reason to use same value for max and min.

**Comment by LuisM000** [comment]
Thanks @halkar, it will be useful to me :)

**Comment by halkar** [comment]
fixed 0.7.7

**Comment by LuisM000** [comment]
Can you solve it in 0.6.XX (0.6.19) version??
Thank you.
Greetings,

Luis

**Comment by halkar** [comment]
@LuisM000 no. Why do you need 0.6.x?

**Comment by LuisM000** [comment]
@halkar currently, by project requirements, I can not upgrade Xamarin.RangeSlider to 0.7.x version, I must remain in 0.6.x version.
Sorry :(

Greetings,
Luis

**Comment by halkar** [comment]
@LuisM000 then you will have to make sure that max and min value are always different (even smallest epsilon will do).
